### ISSUE TITLE
Implement the `subtraction` functionality for the calculator

### ISSUE THREAD

**Issue by bogdandit** [BoiseState/CS-HU271-Assignments-Kanban#1]
**TODO**:
- [ ] Write a few unit tests in the `operations.test.js`
- [ ] Implement the `subtract` method in the `operations.js`
- [ ] In a terminal, run `npm test` and make sure the test suite is green and all tests are passing. If there are any tests failing, make changes to the unit tests or the implementation until the test suite is green.
- [ ] commit the unit tests and the implementation in the same commit and establish the traceability between the commit and task (e.g., `Implements #task_id`)
