### ISSUE TITLE
Implement new (miscellaneous) routes in the Web Server

### ISSUE THREAD

**Issue by bogdandit** [BoiseState/CS-HU271-Assignments-Kanban#2]
**TODO**:
- [ ] Implement new routes in the `app.js`
- [ ] Write a few unit tests in `app.test.js` to test the new routes
- [ ] In a terminal, run `npm test` and make sure the test suite is green and all tests are passing. If there are any tests failing, make changes to the unit tests or the implementation until the test suite is green.
- [ ] commit the unit tests and the implementation in the same commit and establish the traceability between the commit and task (e.g., `Implements #task_id`)
